# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sitaramshelke.github.io
baseurl: /
title: Sitaram Shelke
author: Sitaram Shelke
description: Personal blog and resume
avatar: profile.png
email: sitaramshelke@gmail.com
github: sitaramshelke
twitter: sitaramshelke
linkedin: sitaramshelke
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: sitaramsblog
google_analytics: UA-72761937-1


# needed for travis-ci build
#exclude: [vendor]
